baseURL = "https://angelostavrow.com/"
title = "Angelo Stavrow"
copyright = "© 2020 Angelo Stavrow"
languageCode = "en-CA"
theme = "indigo"

# We use true Markdown as a subset of HTML so this is necessary to enable iframes and scripts.
[markup.goldmark.renderer]
  unsafe = true

[params]
  Author = "Angelo Stavrow"
  Description = "Angelo Stavrow's personal website"
  Subtitle = "A personal internet website"
  Avatar = "images/avatar.jpg"
  Biography = "Tinkerer with a strong interest for development, of both the personal and software persuasion; easily defeated with spatulas. Equal measures enthusiasm and concern for tech's effect on the world. He/him."
  ShowBio = true
  PermalinkText = "⏳"
  mainSections = ["post", "update"]
  paymentPointer = "$pay.stronghold.co/1a14ae3172cd9ad4482a8de42fbdb90f7ac"

  # Contact/social-network identifiers for social icons
  EmailAddress = "contact@angelostavrow.com"
  FlickrUser = "astavrow"
  GitHubUser = "AngeloStavrow"
  GlitchUser = "AngeloStavrow"
  LinkedInUser = "astavrow"
  MicroBlogUser = "angelostavrow"
  StackOverflowUser = "1234545"
  TwitterUser = "AngeloStavrow"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "contact@angelostavrow.com"
    FlickrUser = "astavrow"
    GitHubUser = "AngeloStavrow"
    TwitterUser = "AngeloStavrow"
    MicroBlogUser = "angelostavrow"
    Country = "Canada"
    City = "Montreal"