baseURL = "https://angelostavrow.com/"
title = "Angelo Stavrow"
copyright = "Copyright © 2018, Angelo Stavrow"
languageCode = "en-CA"
theme = "indigo"

[params]
  Author = "Angelo Stavrow"
  Description = "Angelo Stavrow's personal website"
  Subtitle = "A personal internet website"
  Avatar = "images/avatar.jpg"
  Biography = "Tinkerer with a strong interest for development, of both the personal and software persuasion; easily defeated with spatulas. Equal measures enthusiasm and concern for tech's effect on the world. He/him."
  ShowBio = true
  PermalinkText = "⏳"

  # Contact/social-network identifiers for social icons
  EmailAddress = "contact@angelostavrow.com"
  FlickrUser = "astavrow"
  GitHubUser = "AngeloStavrow"
  GitLabUser = "AngeloStavrow"
  GlitchUser = "AngeloStavrow"
  KeybaseUser = "astavrow"
  LinkedInUser = "astavrow"
  MicroBlogUser = "angelostavrow"
  StackOverflowUser = "1324545"
  TwitterUser = "AngeloStavrow"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "contact@angelostavrow.com"
    FlickrUser = "astavrow"
    GitHubUser = "AngeloStavrow"
    TwitterUser = "AngeloStavrow"
    MicroBlogUser = "angelostavrow"
    Country = "Canada"
    City = "Montreal"